/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Accounts;

import List.StudentList;
import Login.LoginForm;
import crediblecollegiatemanagementsystem.Student;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author hp2
 */
public class ListOfPaidAndUnPaidStudents extends javax.swing.JFrame {

     public        StudentList sObj=new StudentList();
 public    LoginForm ObjectCopy=new LoginForm();
 int noOfLatePaidStudents=0,noOfPaidStudents=0;
    /**
     * Creates new form ListOfPaidAndUnPaidStudents
     */
    public ListOfPaidAndUnPaidStudents() {
        
        initComponents();
        ObjectCopy.objectAddition();
        this.sObj=ObjectCopy.sObj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("PAID STUDENTS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 170, 140, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("LATE STUDENTS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 210, 140, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/L2.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 0, 250, 110);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECT ONE OF THE FOLLOWING");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 130, 260, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/texture_background_pattern_line_55307_3840x2400.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-6, 0, 410, 300);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    public void check()
//    {
//    int noOfLatePaidStudents=0,noOfPaidStudents=0;
//         JTextArea area = new JTextArea();
//          Student[] paid=new Student[sObj.count];
//        Student[] late=new Student[sObj.count];
//            for(int i=0;i<sObj.count;i++)
//        {
//            if("L".equals(sObj.sList[i].getFeeStatus()))
//            { late[noOfLatePaidStudents]=sObj.sList[i]; 
//            noOfLatePaidStudents++;    }
//            else
//                {paid[noOfPaidStudents]= sObj.sList[i]; 
//                noOfPaidStudents++;}
//            }
//
//
////                JOptionPane.showMessageDialog(null,"late paid students list"+late[i].toString());
//                
//            for(int i=0;i<noOfLatePaidStudents;i++)
//    {
//            area.append(i + "     " + late[i].toString()+"\n");
//    }
//    add(area);
//    
//    ListOfPaidAndUnPaidStudents gui = new ListOfPaidAndUnPaidStudents();
////        gui.check();
////         gui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
////         gui.setSize(400,200);
////         gui.setVisible(true);
//            
//    
//    
//    
//        }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
//        this.check();
        
//         JTextArea area = new JTextArea();
          Student[] paid=new Student[sObj.count];
        Student[] late=new Student[sObj.count];
            for(int i=0;i<sObj.count;i++)
        {
            if("L".equals(sObj.sList[i].getFeeStatus()))
            { late[noOfLatePaidStudents]=sObj.sList[i]; 
            noOfLatePaidStudents++;    }
           
            }


            for(int i=0;i<noOfLatePaidStudents;i++)
                JOptionPane.showMessageDialog(null,"late paid students list"+late[i].toString());
                
            noOfLatePaidStudents=0;
//    {
//            area.append(i + "     " + late[i].toString()+"\n");
//    }
//    add(area);
////            
////        
    }//GEN-LAST:event_jButton2ActionPerformed

        
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
           Student[] paid=new Student[sObj.count];
        Student[] late=new Student[sObj.count];
            for(int i=0;i<sObj.count;i++)
        {
            if("p".equals(sObj.sList[i].getFeeStatus()))
            { paid[noOfPaidStudents]= sObj.sList[i]; 
                noOfPaidStudents++;    }
//            else
//                {paid[noOfPaidStudents]= sObj.sList[i]; 
//                noOfPaidStudents++;}
            }
            
            for(int i=0;i<noOfPaidStudents;i++)
                JOptionPane.showMessageDialog(null,"late paid students list "+paid[i].toString());
            
       noOfPaidStudents=0;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfPaidAndUnPaidStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfPaidAndUnPaidStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfPaidAndUnPaidStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfPaidAndUnPaidStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//         gui.setVisible(true);
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
        /* Create and display the form */
            public void run() {
//        ListOfPaidAndUnPaidStudents gui = new ListOfPaidAndUnPaidStudents();
       
                new ListOfPaidAndUnPaidStudents().setVisible(true);
            }
        });
//ListOfPaidAndUnPaidStudents call =new ListOfPaidAndUnPaidStudents();
// call.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//JFrame calll=new JFrame();

   
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
